server:
  port: 8081 # 访问端口
spring:
  datasource:
    # url 是数据库连接配置，固定的
    url: jdbc:mysql://localhost:8889/hm_filesystem?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root # 数据库账户
    password: root # 数据库密码
    driver-class-name: com.mysql.cj.jdbc.Driver # 数据库连接驱动
  servlet:
    multipart:
      max-request-size: 1000MB # 单次POSt请求内容大小
      max-file-size: 1000MB # 单个文件最大上传大小
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true # 开启数据表驼峰命名
filesystem:
  src: file/